version: 2

models:
  - name: CARE_SITE
    columns:
      - name: care_site_id
        tests:
          - unique
          - not_null

  - name: CONDITION_OCCURRENCE
    columns:
      - name: condition_occurrence_id
        tests:
          - unique
          - not_null
      - name: person_id
        tests:
          - not_null
          - relationships:
              to: ref('PERSON')
              field: person_id
      - name: provider_id
        tests:
          - not_null
          - relationships:
              to: ref('PROVIDER')
              field: provider_id
      - name: visit_occurrence_id
        tests:
          - not_null
          - relationships:
              to: ref('VISIT_OCCURRENCE')
              field: visit_occurrence_id

      - name: visit_detail_id
        tests:
          - relationships:
              to: ref('VISIT_DETAIL')
              field: visit_detail_id


  - name: DEATH
    columns:
      - name: person_id
        tests:
          - unique
          - not_null
          - relationships:
              to: ref('PERSON')
              field: person_id
      - name: death_date
        tests:
          - not_null

  - name: DEVICE_EXPOSURE
    columns:
      - name: device_exposure_id
        tests:
          - unique
          - not_null
      - name: person_id
        tests:
          - not_null
          - relationships:
              to: ref('PERSON')
              field: person_id
      - name: visit_occurrence_id
        tests:
          - relationships:
              to: ref('VISIT_OCCURRENCE')
              field: visit_occurrence_id
      - name: visit_detail_id
        tests:
          - relationships:
              to: ref('VISIT_DETAIL')
              field: visit_detail_id

  - name: DRUG_EXPOSURE
    columns:
      - name: drug_exposure_id
        tests:
          - unique
          - not_null
      - name: person_id
        tests:
          - not_null
          - relationships:
              to: ref('PERSON')
              field: person_id
      - name: provider_id
        tests:
          - relationships:
              to: ref('PROVIDER')
              field: provider_id
      - name: visit_occurrence_id
        tests:
          - not_null
          - relationships:
              to: ref('VISIT_OCCURRENCE')
              field: visit_occurrence_id
      - name: visit_detail_id
        tests:
          - relationships:
              to: ref('VISIT_DETAIL')
              field: visit_detail_id

  - name: LOCATION
    columns:
      - name: location_id
        tests:
          - unique
          - not_null

  - name: MEASUREMENT
    columns:
      - name: measurement_id
        tests:
          - unique
          - not_null
      - name: person_id
        tests:
          - not_null
          - relationships:
              to: ref('PERSON')
              field: person_id
      - name: visit_occurrence_id
        tests:
          - not_null
          - relationships:
              to: ref('VISIT_OCCURRENCE')
              field: visit_occurrence_id
      - name: provider_id
        tests:
          - relationships:
              to: ref('provider')
              field: provider_id
      - name: visit_detail_id
        tests:
          - relationships:
              to: ref('VISIT_DETAIL')
              field: visit_detail_id

  - name: OBSERVATION
    columns:
      - name: observation_id
        tests:
          - unique
          - not_null
      - name: person_id
        tests:
          - not_null
          - relationships:
              to: ref('PERSON')
              field: person_id
      - name: visit_occurrence_id
        tests:
          - relationships:
              to: ref('VISIT_OCCURRENCE')
              field: visit_occurrence_id
      - name: provider_id
        tests:
          - relationships:
              to: ref('PROVIDER')
              field: provider_id
      - name: visit_detail_id
        tests:
          - relationships:
              to: ref('VISIT_DETAIL')
              field: visit_detail_id

  - name: OBSERVATION_PERIOD
    columns:
      - name: observation_period_id
        tests:
          - unique
          - not_null
      - name: person_id
        tests:
          - not_null
          - relationships:
              to: ref('PERSON')
              field: person_id

  - name: PERSON
    columns:
      - name: person_id
        tests:
          - unique
          - not_null
      - name: location_id
        tests:
          - relationships:
              to: ref('LOCATION')
              field: location_id
      - name: provider_id
        tests:
          - relationships:
              to: ref('PROVIDER')
              field: provider_id
      - name: care_site_id
        tests:
          - relationships:
              to: ref('CARE_SITE')
              field: care_site_id

  - name: PROCEDURE_OCCURRENCE
    columns:
      - name: procedure_occurrence_id
        tests:
          - unique
          - not_null
      - name: person_id
        tests:
          - not_null
          - relationships:
              to: ref('PERSON')
              field: person_id
      - name: visit_occurrence_id
        tests:
          - not_null
          - relationships:
              to: ref('VISIT_OCCURRENCE')
              field: visit_occurrence_id
      - name: provider_id
        tests:
          - relationships:
              to: ref('PROVIDER')
              field: provider_id
      - name: visit_detail_id
        tests:
          - relationships:
              to: ref('VISIT_DETAIL')
              field: visit_detail_id

  - name: PROVIDER
    columns:
      - name: provider_id
        tests:
          - unique
          - not_null
      - name: care_site_id
        tests:
          - relationships:
              to: ref('CARE_SITE')
              field: care_site_id

  - name: VISIT_OCCURRENCE
    columns:
      - name: visit_occurrence_id
        tests:
          - unique
          - not_null
      - name: person_id
        tests:
          - not_null
          - relationships:
              to: ref('PERSON')
              field: person_id
      - name: provider_id
        tests:
          - relationships:
              to: ref('PROVIDER')
              field: provider_id
      - name: care_site_id
        tests:
          - relationships:
              to: ref('CARE_SITE')
              field: care_site_id